trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git remote remove github || true
    git remote add github https://$(GITHUB_PAT)@github.com/SimBhamra10/ADBLifeScienceProject.git
    git fetch github
    git pull github main --allow-unrelated-histories
    git push github HEAD:main
  displayName: "Sync with GitHub"