trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0   # 🔥 THIS IS THE FIX

- script: |
    git remote remove github || true
    git remote add github https://$(GITHUB_PAT)@github.com/SimBhamra10/ADBLifeScienceProject.git
    git push github HEAD:main --force
  displayName: "Force push to GitHub"